//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spots.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spots.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string lbl_AreYouSure {
            get {
                return ResourceManager.GetString("lbl_AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdate:.
        /// </summary>
        internal static string lbl_BirthdateField {
            get {
                return ResourceManager.GetString("lbl_BirthdateField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery.
        /// </summary>
        internal static string lbl_Discovery {
            get {
                return ResourceManager.GetString("lbl_Discovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@mail.com.
        /// </summary>
        internal static string lbl_eMailPlaceHolder {
            get {
                return ResourceManager.GetString("lbl_eMailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        internal static string lbl_Feed {
            get {
                return ResourceManager.GetString("lbl_Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string lbl_FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("lbl_FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string lbl_LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("lbl_LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string lbl_LogIn {
            get {
                return ResourceManager.GetString("lbl_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string lbl_LogOut {
            get {
                return ResourceManager.GetString("lbl_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Praises.
        /// </summary>
        internal static string lbl_MyPraises {
            get {
                return ResourceManager.GetString("lbl_MyPraises", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string lbl_MyProfile {
            get {
                return ResourceManager.GetString("lbl_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string lbl_Next {
            get {
                return ResourceManager.GetString("lbl_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string lbl_No {
            get {
                return ResourceManager.GetString("lbl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        internal static string lbl_Or {
            get {
                return ResourceManager.GetString("lbl_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        internal static string lbl_Preferences {
            get {
                return ResourceManager.GetString("lbl_Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **********.
        /// </summary>
        internal static string lbl_PwdPlaceHolder {
            get {
                return ResourceManager.GetString("lbl_PwdPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string lbl_Register {
            get {
                return ResourceManager.GetString("lbl_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm email:.
        /// </summary>
        internal static string lbl_RegisterConfirmEmailField {
            get {
                return ResourceManager.GetString("lbl_RegisterConfirmEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password:.
        /// </summary>
        internal static string lbl_RegisterConfirmPasswordField {
            get {
                return ResourceManager.GetString("lbl_RegisterConfirmPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email:.
        /// </summary>
        internal static string lbl_RegisterEmailField {
            get {
                return ResourceManager.GetString("lbl_RegisterEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name:.
        /// </summary>
        internal static string lbl_RegisterFirstName {
            get {
                return ResourceManager.GetString("lbl_RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name:.
        /// </summary>
        internal static string lbl_RegisterLastName {
            get {
                return ResourceManager.GetString("lbl_RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Password:.
        /// </summary>
        internal static string lbl_RegisterPasswordField {
            get {
                return ResourceManager.GetString("lbl_RegisterPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string lbl_Save {
            get {
                return ResourceManager.GetString("lbl_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        internal static string lbl_UserData {
            get {
                return ResourceManager.GetString("lbl_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string lbl_Yes {
            get {
                return ResourceManager.GetString("lbl_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Placeholder--.
        /// </summary>
        internal static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to want to log out?.
        /// </summary>
        internal static string txt_ConfirmLogOut {
            get {
                return ResourceManager.GetString("txt_ConfirmLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your account.
        /// </summary>
        internal static string txt_LogIn {
            get {
                return ResourceManager.GetString("txt_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or both fields are empty. Please fill the information correctly..
        /// </summary>
        internal static string txt_LogInError_EmptyEntry {
            get {
                return ResourceManager.GetString("txt_LogInError_EmptyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email and password provided do not match with any user registered..
        /// </summary>
        internal static string txt_LogInError_WrongCredentials {
            get {
                return ResourceManager.GetString("txt_LogInError_WrongCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email provided in the &apos;Email&apos; and &apos;Confirm Email&apos; fields must be the same. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_EmailsDontMatch {
            get {
                return ResourceManager.GetString("txt_RegisterError_EmailsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields are empty. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_EmptyFields {
            get {
                return ResourceManager.GetString("txt_RegisterError_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The birthdate provided is not valid. Make sure you are above 12 years of age..
        /// </summary>
        internal static string txt_RegisterError_InvalidBirthdate {
            get {
                return ResourceManager.GetString("txt_RegisterError_InvalidBirthdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The eMail provided is invalid. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_InvalidEmail {
            get {
                return ResourceManager.GetString("txt_RegisterError_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password must be at least 8 characters long..
        /// </summary>
        internal static string txt_RegisterError_InvalidPasswordLength {
            get {
                return ResourceManager.GetString("txt_RegisterError_InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords provided in the &apos;Password&apos; and &apos;Confirm Password&apos; fields must be the same. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("txt_RegisterError_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while trying to register your account, please verify your information and tray again later..
        /// </summary>
        internal static string txt_RegisterError_RegisterError {
            get {
                return ResourceManager.GetString("txt_RegisterError_RegisterError", resourceCulture);
            }
        }
    }
}
