//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spots.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spots.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a example@mail.com.
        /// </summary>
        internal static string lbl_eMailPlaceHolder {
            get {
                return ResourceManager.GetString("lbl_eMailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name.
        /// </summary>
        internal static string lbl_FirstNamePlaceHolder {
            get {
                return ResourceManager.GetString("lbl_FirstNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name.
        /// </summary>
        internal static string lbl_LastNamePlaceHolder {
            get {
                return ResourceManager.GetString("lbl_LastNamePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string lbl_LogIn {
            get {
                return ResourceManager.GetString("lbl_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Or.
        /// </summary>
        internal static string lbl_Or {
            get {
                return ResourceManager.GetString("lbl_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a **********.
        /// </summary>
        internal static string lbl_PwdPlaceHolder {
            get {
                return ResourceManager.GetString("lbl_PwdPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string lbl_Register {
            get {
                return ResourceManager.GetString("lbl_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm email:.
        /// </summary>
        internal static string lbl_RegisterConfirmEmailField {
            get {
                return ResourceManager.GetString("lbl_RegisterConfirmEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password:.
        /// </summary>
        internal static string lbl_RegisterConfirmPasswordField {
            get {
                return ResourceManager.GetString("lbl_RegisterConfirmPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Email:.
        /// </summary>
        internal static string lbl_RegisterEmailField {
            get {
                return ResourceManager.GetString("lbl_RegisterEmailField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a First Name:.
        /// </summary>
        internal static string lbl_RegisterFirstName {
            get {
                return ResourceManager.GetString("lbl_RegisterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Last Name:.
        /// </summary>
        internal static string lbl_RegisterLastName {
            get {
                return ResourceManager.GetString("lbl_RegisterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Password:.
        /// </summary>
        internal static string lbl_RegisterPasswordField {
            get {
                return ResourceManager.GetString("lbl_RegisterPasswordField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a --Placeholder--.
        /// </summary>
        internal static string TEST {
            get {
                return ResourceManager.GetString("TEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in to your account.
        /// </summary>
        internal static string txt_LogIn {
            get {
                return ResourceManager.GetString("txt_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or both fields are empty. Please fill the information correctly..
        /// </summary>
        internal static string txt_LogInError_EmptyEntry {
            get {
                return ResourceManager.GetString("txt_LogInError_EmptyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email provided in the &apos;Email&apos; and &apos;Confirm Email&apos; fields must be the same. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_EmailsDontMatch {
            get {
                return ResourceManager.GetString("txt_RegisterError_EmailsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One or more fields are empty. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_EmptyFields {
            get {
                return ResourceManager.GetString("txt_RegisterError_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The eMail provided is invalid. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_InvalidEmail {
            get {
                return ResourceManager.GetString("txt_RegisterError_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your password must be at least 8 characters long..
        /// </summary>
        internal static string txt_RegisterError_InvalidPasswordLength {
            get {
                return ResourceManager.GetString("txt_RegisterError_InvalidPasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The passwords provided in the &apos;Password&apos; and &apos;Confirm Password&apos; fields must be the same. Please fill the information correctly..
        /// </summary>
        internal static string txt_RegisterError_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("txt_RegisterError_PasswordsDontMatch", resourceCulture);
            }
        }
    }
}
