//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spots_v01.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spots_v01.Recursos.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Or.
        /// </summary>
        internal static string lbl_alternativa {
            get {
                return ResourceManager.GetString("lbl_alternativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a example@mail.com.
        /// </summary>
        internal static string lbl_eMailPlaceHolder {
            get {
                return ResourceManager.GetString("lbl_eMailPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log In.
        /// </summary>
        internal static string lbl_IniciarSesion {
            get {
                return ResourceManager.GetString("lbl_IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        internal static string lbl_PwdPlaceHolder {
            get {
                return ResourceManager.GetString("lbl_PwdPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        internal static string lbl_Registrarse {
            get {
                return ResourceManager.GetString("lbl_Registrarse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome!.
        /// </summary>
        internal static string txt_Bienvenido {
            get {
                return ResourceManager.GetString("txt_Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in to your account.
        /// </summary>
        internal static string txt_IniciarSesion {
            get {
                return ResourceManager.GetString("txt_IniciarSesion", resourceCulture);
            }
        }
    }
}
