//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spots.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Colors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Colors() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spots.Recursos.Colors", typeof(Colors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #FFFFFF.
        /// </summary>
        internal static string cl_BackGround {
            get {
                return ResourceManager.GetString("cl_BackGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #FFA500.
        /// </summary>
        internal static string cl_MainBrand {
            get {
                return ResourceManager.GetString("cl_MainBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #757575.
        /// </summary>
        internal static string cl_MainGray {
            get {
                return ResourceManager.GetString("cl_MainGray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #FF0000.
        /// </summary>
        internal static string cl_TextError {
            get {
                return ResourceManager.GetString("cl_TextError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #202020.
        /// </summary>
        internal static string cl_TextOnBG {
            get {
                return ResourceManager.GetString("cl_TextOnBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #FFFFFF.
        /// </summary>
        internal static string cl_TextOnElse {
            get {
                return ResourceManager.GetString("cl_TextOnElse", resourceCulture);
            }
        }
    }
}
